language: cpp
compiler:
  - gcc

before_script:
  - sudo pip install cpp-coveralls
  - cmake . -DCMAKE_BUILD_TYPE=Debug -DENABLE_GCOV=ON

script:
  - cmake --build .
  - ctest
  - mkdir gcov
  - find -name "*.gc*" -exec mv {} gcov/ \;
  - gcov -d -o gcov/*.gcda
  - coveralls --exclude tests --exclude-pattern '.*CMake[^/]+\.c(?:pp)?' --exclude-pattern 'CheckTypeSize/[^/]+\.c(?:pp)
