SET(UNITTEST11_TESTS_SRC_FILES main.cpp
                               Examples/EventDispatcher.cpp
                               Examples/Minesweeper.cpp
                               Unit/MockTests.cpp
                               Unit/TestFixtureTests.cpp
                               Unit/Assert/FailTests.cpp
                               Unit/Assert/ThatTests.cpp
                               Unit/detail/LogicalOperandsTests.cpp
                               Unit/detail/MockArgumentHandlerTests.cpp
                               Unit/detail/MockReturnHandlerTests.cpp
                               Unit/detail/OperandTests.cpp
                               Unit/detail/TestFixtureRunnerTests.cpp
                               Unit/detail/TestStageBuilderTests.cpp
                               Unit/detail/TestStageTests.cpp
                               Unit/Is/AnyTests.cpp
                               Unit/Is/BetweenTests.cpp
                               Unit/Is/EmptyTests.cpp
                               Unit/Is/EqualToTests.cpp
                               Unit/Is/FalseTests.cpp
                               Unit/Is/GreaterThanTests.cpp
                               Unit/Is/InfinityTests.cpp
                               Unit/Is/LessThanTests.cpp
                               Unit/Is/NaNTests.cpp
                               Unit/Is/NullTests.cpp
                               Unit/Is/TrueTests.cpp
                               Unit/Is/ZeroTests.cpp
                               Unit/Is/Iterable/EquivalentToTests.cpp
                               Unit/Is/Iterable/OfTests.cpp
                               Unit/Is/Iterable/Containing/ItemTests.cpp
                               Unit/Is/Iterable/Containing/SubsetTests.cpp
                               Unit/Is/String/BeginningWithTests.cpp
                               Unit/Is/String/ContainingTests.cpp
                               Unit/Is/String/EndingWithTests.cpp
                               Unit/out/StdOutputTests.cpp
                               Unit/Utility/ToStringTests.cpp
                               Unit/Will/PassTests.cpp
                               Unit/Will/ThrowTests.cpp)
