SET (UNITTEST11_INCLUDE_FILES ${UNITTEST11_SOURCE_DIR}/UnitTest11.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Category.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Core.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Macros.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Mock.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Run.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/TestFixture.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Assert/Fail.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Assert/That.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/detail/AndOperand.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/detail/BaseOperand.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/detail/DeclareFixture.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/detail/MockArgumentHandler.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/detail/MockReturnHandler.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/detail/MockTimesVerify.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/detail/MockVerify.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/detail/NotOperand.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/detail/OrOperand.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/detail/TestFailedException.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/detail/TestFixtureAbstract.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/detail/TestFixtureResults.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/detail/TestFixtureRunner.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/detail/TestStage.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/detail/TestStageBuilder.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/detail/TestStageBuilderImpl.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/detail/TestStageImpl.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/detail/TestStep.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Is/Any.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Is/Between.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Is/Empty.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Is/EqualTo.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Is/False.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Is/GreaterThan.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Is/Infinity.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Is/LessThan.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Is/NaN.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Is/Null.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Is/True.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Is/Zero.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Is/Iterable/EquivalentTo.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Is/Iterable/Of.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Is/Iterable/Containing/Item.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Is/Iterable/Containing/Subset.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Is/String/BeginningWith.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Is/String/Containing.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Is/String/EndingWith.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/out/Output.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/out/StdOutput.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/utility/AreEqual.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/utility/DefaultValue.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/utility/ToString.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/utility/Meta/IfElseTypes.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/utility/Meta/IsIterableContainer.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/utility/Meta/IsIterableOfType.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Will/Pass.hpp
							  ${UNITTEST11_SOURCE_DIR}/UnitTest11/Will/Throw.hpp)

SET (UNITTEST11_SRC_FILES ${UNITTEST11_SOURCE_DIR}/src/Run.cpp
                          ${UNITTEST11_SOURCE_DIR}/src/TestFixture.cpp
                          ${UNITTEST11_SOURCE_DIR}/src/Assert/Fail.cpp
                          ${UNITTEST11_SOURCE_DIR}/src/detail/DeclareFixture.cpp
                          ${UNITTEST11_SOURCE_DIR}/src/detail/GetRunner.cpp
                          ${UNITTEST11_SOURCE_DIR}/src/detail/TestFixtureRunner.cpp
                          ${UNITTEST11_SOURCE_DIR}/src/detail/TestStage.cpp
                          ${UNITTEST11_SOURCE_DIR}/src/detail/TestStageBuilder.cpp
                          ${UNITTEST11_SOURCE_DIR}/src/detail/TestStageBuilderImpl.cpp
                          ${UNITTEST11_SOURCE_DIR}/src/detail/TestStageImpl.cpp
                          ${UNITTEST11_SOURCE_DIR}/src/Is/Empty.cpp
                          ${UNITTEST11_SOURCE_DIR}/src/Is/False.cpp
                          ${UNITTEST11_SOURCE_DIR}/src/Is/Infinity.cpp
                          ${UNITTEST11_SOURCE_DIR}/src/Is/NaN.cpp
                          ${UNITTEST11_SOURCE_DIR}/src/Is/Null.cpp
                          ${UNITTEST11_SOURCE_DIR}/src/Is/True.cpp
                          ${UNITTEST11_SOURCE_DIR}/src/Is/Zero.cpp
                          ${UNITTEST11_SOURCE_DIR}/src/out/Output.cpp
                          ${UNITTEST11_SOURCE_DIR}/src/out/StdOutput.cpp)
